"""create tables

Revision ID: 11dfe48389f7
Revises: 4a826cfb8bdc
Create Date: 2025-12-01 15:57:54.995451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11dfe48389f7'
down_revision: Union[str, Sequence[str], None] = '4a826cfb8bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'caption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('caption', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
