"""create tables

Revision ID: 4a826cfb8bdc
Revises: a12b388fcf5c
Create Date: 2025-12-01 15:32:32.952021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a826cfb8bdc'
down_revision: Union[str, Sequence[str], None] = 'a12b388fcf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('caption', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'caption')
    # ### end Alembic commands ###
